spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/kuchat
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mustache:
    check-template-location: false

secret:
  jwt-secret-key: vlkhpfeicviusdfslfhlwbfvcabmwefsdfeoivnsdmewv
  jwt-expired-in: 7200000

server:
  port: 9000
